name: vampire_survivor
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.37.0  # <--- Verifique se esta linha está correta
  google_fonts: ^8.1.0

flutter:
  uses-material-design: true

  # Adicione exatamente estas duas linhas abaixo:
  assets:
    - assets/images/